name: frozennotes
description: A new Flutter project for note taking.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. 
publish_to: 'none' 

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.1+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.9.0
  firebase_auth: ^4.4.0
  cloud_firestore: ^4.5.0
  firebase_analytics: ^10.2.0
  sqflite: ^2.2.6
  path_provider: ^2.0.14
  path: ^1.8.2
  share_plus: ^6.3.2
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  firebase_crashlytics: ^3.1.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  test: ^1.22.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true